### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dataset/'

### ISSUE THREAD

**Issue by git-sohib** [kcct-fujimotolab/3DCNN#11]
I am running
`python 3dcnn.py --batch 32 --epoch 50 --videos dataset/ --nclass 10 --output 3dcnnresult/ --color True --skip False --depth 15 `
as shown in demo, and received the above error. before that I inserted the path to the variable manually like `video_dir = "D:\\\\user\\Action_Recognition\\UCF-101" # manually added `
The full error 

`Traceback (most recent call last):
  File "3dcnn.py", line 182, in <module>
    main()
  File "3dcnn.py", line 124, in main
    args.output, args.color, args.skip)
  File "3dcnn.py", line 63, in loaddata
    files = os.listdir(video_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dataset/'`

**Comment by bzc220** [comment]
You must download the UCF101 dataset and then change the --videos dataset/ to --videos UCF101/

**Comment by yanfei-zhang-95** [comment]
However, when I use the UCF101 dataset, the dataset cannot be loaded properly as it cannot reach any video with the original code.

**Comment by lmhlmh1282** [comment]
You must put videos outside subfolders , which addresses vid dir  error . ALL the videos should be in one folder.

**Comment by shadowwu1** [comment]
> You must put videos outside subfolders , which addresses vid dir error . ALL the videos should be in one folder.

the UCF101 has 101 classes and there are 101 subfolders in UCF101 root folder,  do you mean I should put all videos from 101 subfolders in one folder?

**Comment by yuzeWAN** [comment]
> 

excuse me,I have the same question as yours, have you solve this problems?
